version: "3.8"

volumes:
  mysql_db:

services:

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: banking
      MYSQL_USER: banking-user
      MYSQL_PASSWORD: userpw
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55